version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - m1guelpf
  ignore:
  - dependency-name: open
    versions:
    - 8.0.2
    - 8.0.4
    - 8.0.5
  - dependency-name: conf
    versions:
    - 9.0.0
    - 9.0.1
    - 9.0.2
  - dependency-name: "@hapi/hapi"
    versions:
    - 20.0.3
    - 20.1.0
  - dependency-name: ora
    versions:
    - 5.3.0
